version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    allow:
      - dependency-type: all
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"
