name: Build and push Docker images for a LLVM version, base image, and configuration

on:
  workflow_call:
    inputs:
      llvm-version:
        type: string
      base-image-tag:
        type: string
      llvm-configuration:
        type: string
      push:
        type: boolean

concurrency:
  group: ${{ github.workflow }}-build-${{ inputs.llvm-version }}-${{ inputs.base-image-tag }}-${{ inputs.llvm-configuration }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DOCKERHUB_USERNAME: zhongruoyu
  DOCKERHUB_REPOSITORY: zhongruoyu/llvm-ports
  GHCR_USERNAME: zhongruoyu
  GHCR_REPOSITORY: ghcr.io/zhongruoyu/llvm-ports
  BUILD_CACHE_REPOSITORY: ghcr.io/zhongruoyu/llvm-ports/cache
  LLVM_VERSION: ${{ inputs.llvm-version }}
  BASE_IMAGE_TAG: ${{ inputs.base-image-tag }}
  LLVM_CONFIGURATION: ${{ inputs.llvm-configuration }}
  BUILD_CONFIG: ${{ inputs.llvm-version }}${{ inputs.llvm-configuration == 'slim' && '-slim' || '' }}-${{ inputs.base-image-tag }}

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.metadata.outputs.tags }}
      labels: ${{ steps.metadata.outputs.labels }}
    steps:
      - name: Determine metadata
        id: metadata
        uses: docker/metadata-action@80c7e94dd9b9319bd5eb7a0e0fe9291e23a2a2e9 # v6.1.0
        with:
          images: |
            ${{ env.DOCKERHUB_REPOSITORY }}
            ${{ env.GHCR_REPOSITORY }}
          flavor: |
            latest=false
            suffix=${{ inputs.llvm-configuration == 'slim' && '-slim' || '' }}-${{ env.BASE_IMAGE_TAG }}
          tags: |
            type=pep440,value=${{ env.LLVM_VERSION }},pattern={{version}}
            type=pep440,value=${{ env.LLVM_VERSION }},pattern={{major}}.{{minor}}
            type=pep440,value=${{ env.LLVM_VERSION }},pattern={{major}}

  build:
    needs: metadata
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    name: >
      Build ${{ inputs.llvm-version }} - ${{ inputs.base-image-tag }}
      ${{ inputs.llvm-configuration && format(' ({0})', inputs.llvm-configuration) || '' }}
      (${{ matrix.arch }})
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read
      packages: write
    env:
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf \
            /usr/local/lib/android
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Load build environment
        run: cat build.env >> "$GITHUB_ENV"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Login to Docker Hub
        if: inputs.push
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        if: inputs.push
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ github.token }}
      - name: Set up build
        id: setup
        run: |
          {
            echo "cache_from=type=registry,ref=$BUILD_CACHE_REPOSITORY:$BUILD_CONFIG-$ARCH"
            if [[ "$PUSH" = true ]]; then
              echo "cache_to=type=registry,ref=$BUILD_CACHE_REPOSITORY:$BUILD_CONFIG-$ARCH,mode=max"
              echo "outputs<<OUTPUTS"
              echo "type=image,name=$DOCKERHUB_REPOSITORY,name-canonical=true,push=true,push-by-digest=true"
              echo "type=image,name=$GHCR_REPOSITORY,name-canonical=true,push=true,push-by-digest=true"
              echo "OUTPUTS"
            else
              echo "cache_to="
              echo "outputs="
            fi
          } >> "$GITHUB_OUTPUT"
        env:
          PUSH: ${{ inputs.push }}
      - name: Build and push Docker image by digest
        id: build
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          platforms: linux/${{ matrix.arch }}
          labels: ${{ needs.metadata.outputs.labels }}
          build-args: |
            BASE_IMAGE=public.ecr.aws/docker/library/buildpack-deps:${{ env.BASE_IMAGE_TAG }}
            LLVM_VERSION
            BINUTILS_VERSION
            CMAKE_VERSION
            EXTRA_CMAKE_ARGS=${{ env.LLVM_CONFIGURATION == 'slim' && '-DLLVM_LINK_LLVM_DYLIB=ON' || '' }}
          cache-from: ${{ steps.setup.outputs.cache_from }}
          cache-to: ${{ steps.setup.outputs.cache_to }}
          outputs: ${{ steps.setup.outputs.outputs }}
      - name: Export digest
        run: |
          mkdir -p "$RUNNER_TEMP"/digests
          echo "${DIGEST#sha256:}" > "$RUNNER_TEMP/digests/$BUILD_CONFIG-$ARCH"
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
      - name: Upload digest
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: digest-${{ env.BUILD_CONFIG }}-${{ env.ARCH }}
          path: ${{ runner.temp }}/digests/*

  merge:
    if: inputs.push
    needs: [metadata, build]
    name: >
      Merge ${{ inputs.llvm-version }} - ${{ inputs.base-image-tag }}
      ${{ inputs.llvm-configuration && format(' ({0})', inputs.llvm-configuration) || '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      - name: Login to Docker Hub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ github.token }}
      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-${{ env.BUILD_CONFIG }}-*
          merge-multiple: true
      - name: Create manifest list and push
        run: |
          mapfile -t tags <<< "$TAGS"
          tag_args=()
          for tag in "${tags[@]}"; do
            tag_args+=(--tag="$tag")
          done
          images=(
            "$GHCR_REPOSITORY@sha256:$(cat "$RUNNER_TEMP/digests/$BUILD_CONFIG-x86_64")"
            "$GHCR_REPOSITORY@sha256:$(cat "$RUNNER_TEMP/digests/$BUILD_CONFIG-aarch64")"
          )
          docker buildx imagetools create "${tag_args[@]}" "${images[@]}"
        env:
          TAGS: ${{ needs.metadata.outputs.tags }}
