name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        llvm-version:
          - "22.1.8"
          - "21.1.8"
          - "20.1.8"
          - "19.1.7"
          - "18.1.8"
          - "17.0.6"
          - "16.0.6"
          - "15.0.7"
          - "14.0.6"
          - "13.0.1"
        base-image-tag:
          - trixie
          - bookworm
          - resolute
          - noble
          - jammy
        llvm-configuration:
          - ""
          - slim
    name: Build ${{ matrix.llvm-version }} - ${{ matrix.base-image-tag }}${{ matrix.llvm-configuration && format(' ({0})', matrix.llvm-configuration) || '' }}
    uses: ./.github/workflows/docker-build.yml
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    permissions:
      contents: read
      packages: write # for pushing image and cache
    with:
      llvm-version: ${{ matrix.llvm-version }}
      base-image-tag: ${{ matrix.base-image-tag }}
      llvm-configuration: ${{ matrix.llvm-configuration }}
      push: ${{ github.ref == 'refs/heads/main' }}
