name: Build and push Docker images for a LLVM version, base image, and configuration

on:
  workflow_call:
    inputs:
      llvm-version:
        type: string
      base-image-tag:
        type: string
      llvm-configuration:
        type: string

concurrency:
  group: ${{ github.workflow }}-build-${{ inputs.llvm-version }}-${{ inputs.base-image-tag }}-${{ inputs.llvm-configuration }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_USERNAME: zhongruoyu
  DOCKERHUB_REPOSITORY: zhongruoyu/llvm-ports
  GHCR_USERNAME: zhongruoyu
  GHCR_REPOSITORY: ghcr.io/zhongruoyu/llvm-ports

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
          - aarch64
    name: >
      Build ${{ inputs.llvm-version }} - ${{ inputs.base-image-tag }}
      ${{ inputs.llvm-configuration && format(' ({0})', inputs.llvm-configuration) || '' }}
      (${{ matrix.arch }})
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    permissions:
      contents: read
      packages: write
    env:
      LLVM_VERSION: ${{ inputs.llvm-version }}
      BASE_IMAGE_TAG: ${{ inputs.base-image-tag }}
      ARCH: ${{ matrix.arch }}
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf \
            /usr/local/lib/android
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Load build environment
        run: cat build.env >> "$GITHUB_ENV"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ github.token }}
      - name: Build and push Docker image by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.arch }}
          build-args: |
            BASE_IMAGE=public.ecr.aws/docker/library/buildpack-deps:${{ env.BASE_IMAGE_TAG }}
            LLVM_VERSION
            BINUTILS_VERSION
            CMAKE_VERSION
            EXTRA_CMAKE_ARGS=${{ inputs.llvm-configuration == 'slim' && '-DLLVM_LINK_LLVM_DYLIB=ON' || '' }}
          outputs: |
            type=image,name=${{ env.DOCKERHUB_REPOSITORY }},name-canonical=true,push=true,push-by-digest=true
            type=image,name=${{ env.GHCR_REPOSITORY }},name-canonical=true,push=true,push-by-digest=true
      - name: Export digest
        run: |
          mkdir -p "$RUNNER_TEMP"/digests
          echo "${DIGEST#sha256:}" > "$RUNNER_TEMP/digests/$LLVM_VERSION$CONFIG_SUFFIX-$BASE_IMAGE_TAG-$ARCH"
        env:
          DIGEST: ${{ steps.build.outputs.digest }}
          ARCH: ${{ matrix.arch }}
          CONFIG_SUFFIX: ${{ inputs.llvm-configuration == 'slim' && '-slim' || '' }}
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digest-${{ inputs.llvm-version }}${{ inputs.llvm-configuration == 'slim' && '-slim' || '' }}-${{ inputs.base-image-tag }}-${{ matrix.arch }}
          path: ${{ runner.temp }}/digests/*

  merge:
    needs: build
    name: >
      Merge ${{ inputs.llvm-version }} - ${{ inputs.base-image-tag }}
      ${{ inputs.llvm-configuration && format(' ({0})', inputs.llvm-configuration) || '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      LLVM_VERSION: ${{ inputs.llvm-version }}
      BASE_IMAGE_TAG: ${{ inputs.base-image-tag }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.GHCR_USERNAME }}
          password: ${{ github.token }}
      - name: Download digests
        uses: actions/download-artifact@v5
        with:
          path: ${{ runner.temp }}/digests
          pattern: digest-${{ inputs.llvm-version }}${{ inputs.llvm-configuration == 'slim' && '-slim' || '' }}-${{ inputs.base-image-tag }}-*
          merge-multiple: true
      - name: Create manifest list and push
        run: |
          docker buildx imagetools create \
            --tag="$DOCKERHUB_REPOSITORY:$LLVM_VERSION$CONFIG_SUFFIX-$BASE_IMAGE_TAG" \
            --tag="$DOCKERHUB_REPOSITORY:$(echo "$LLVM_VERSION" | cut -d '.' -f 1-2)$CONFIG_SUFFIX-$BASE_IMAGE_TAG" \
            --tag="$DOCKERHUB_REPOSITORY:$(echo "$LLVM_VERSION" | cut -d '.' -f 1)$CONFIG_SUFFIX-$BASE_IMAGE_TAG" \
            --tag="$GHCR_REPOSITORY:$LLVM_VERSION$CONFIG_SUFFIX-$BASE_IMAGE_TAG" \
            --tag="$GHCR_REPOSITORY:$(echo "$LLVM_VERSION" | cut -d '.' -f 1-2)$CONFIG_SUFFIX-$BASE_IMAGE_TAG" \
            --tag="$GHCR_REPOSITORY:$(echo "$LLVM_VERSION" | cut -d '.' -f 1)$CONFIG_SUFFIX-$BASE_IMAGE_TAG" \
            "$GHCR_REPOSITORY@sha256:$(cat "$RUNNER_TEMP/digests/$LLVM_VERSION$CONFIG_SUFFIX-$BASE_IMAGE_TAG-x86_64")" \
            "$GHCR_REPOSITORY@sha256:$(cat "$RUNNER_TEMP/digests/$LLVM_VERSION$CONFIG_SUFFIX-$BASE_IMAGE_TAG-aarch64")"
        env:
          CONFIG_SUFFIX: ${{ inputs.llvm-configuration == 'slim' && '-slim' || '' }}
