name: Build and push Docker images

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        llvm-version:
          - "21.1.2"
          - "20.1.8"
          - "19.1.7"
          - "18.1.8"
          - "17.0.6"
          - "16.0.6"
          - "15.0.7"
          - "14.0.6"
          - "13.0.1"
          - "12.0.1"
        base-image-tag:
          - trixie
          - bookworm
          - bullseye
          - noble
          - jammy
          - focal
        llvm-configuration:
          - ""
          - slim
    uses: ./.github/workflows/docker-build.yml
    with:
      llvm-version: ${{ matrix.llvm-version }}
      base-image-tag: ${{ matrix.base-image-tag }}
      llvm-configuration: ${{ matrix.llvm-configuration }}
    secrets: inherit
