name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 1 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BINUTILS_VERSION: "2.43.1"
  CMAKE_VERSION: "3.30.5"

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        llvm-version:
          - "19.1.3"
          - "18.1.8"
          - "17.0.6"
          - "16.0.6"
          - "15.0.7"
          - "14.0.6"
          - "13.0.1"
          - "12.0.1"
        base-image-tag:
          - bookworm
          - bullseye
          - noble
          - jammy
          - focal
        llvm-configuration:
          - ""
          - slim
    name: >
      ${{ matrix.llvm-version }} - ${{ matrix.base-image-tag }}
      ${{ matrix.llvm-configuration && format(' ({0})', matrix.llvm-configuration) || '' }}
    env:
      BASE_IMAGE_TAG: ${{ matrix.base-image-tag }}
      LLVM_VERSION: ${{ matrix.llvm-version }}
      CONFIG_SUFFIX: ${{ matrix.llvm-configuration == 'slim' && '-slim' || '' }}
      EXTRA_CMAKE_ARGS: ${{ matrix.llvm-configuration == 'slim' && '-DLLVM_LINK_LLVM_DYLIB=ON' || '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf \
            /usr/local/lib/android
      - name: Determine build attributes
        run: |
          cat <<EOF | tee -a "$GITHUB_ENV"
          LLVM_VERSION_MAJOR=$(echo "${LLVM_VERSION}" | cut -d '.' -f 1)
          LLVM_VERSION_MAJOR_MINOR=$(echo "${LLVM_VERSION}" | cut -d '.' -f 1-2)
          EOF
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: zhongruoyu
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          tags: |
            zhongruoyu/llvm-ports:${{ env.LLVM_VERSION }}${{ env.CONFIG_SUFFIX }}-${{ env.BASE_IMAGE_TAG }}
            zhongruoyu/llvm-ports:${{ env.LLVM_VERSION_MAJOR_MINOR }}${{ env.CONFIG_SUFFIX }}-${{ env.BASE_IMAGE_TAG }}
            zhongruoyu/llvm-ports:${{ env.LLVM_VERSION_MAJOR }}${{ env.CONFIG_SUFFIX }}-${{ env.BASE_IMAGE_TAG }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
            BINUTILS_VERSION=${{ env.BINUTILS_VERSION }}
            CMAKE_VERSION=${{ env.CMAKE_VERSION }}
            LLVM_VERSION=${{ env.LLVM_VERSION }}
            EXTRA_CMAKE_ARGS=${{ env.EXTRA_CMAKE_ARGS }}
          push: true
