name: docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: docker
  cancel-in-progress: true

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        llvm-version:
          - "19.1.3"
          - "18.1.8"
          - "17.0.6"
          - "16.0.6"
          - "15.0.7"
          - "14.0.6"
          - "13.0.1"
          - "12.0.1"
        base-image-tag:
          - bookworm
          - bullseye
          - noble
          - jammy
          - focal
        llvm-configuration:
          - ""
          - slim
    env:
      DOCKERHUB_REPOSITORY: zhongruoyu/llvm-ports
      PLATFORMS: linux/amd64
      BINUTILS_VERSION: "2.42"
      CMAKE_VERSION: "3.30.5"
    name: >
      ${{ matrix.llvm-version }} - ${{ matrix.base-image-tag }}
      ${{ matrix.llvm-configuration && format('- {0}', matrix.llvm-configuration) || '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf \
            /usr/local/lib/android
      - name: Set environment variables
        run: |
          cat <<EOF | tee -a "$GITHUB_ENV"
          BASE_IMAGE_TAG=${{ matrix.base-image-tag }}
          LLVM_VERSION=${{ matrix.llvm-version }}
          LLVM_VERSION_MAJOR=$(echo "${{ matrix.llvm-version }}" | cut -d '.' -f 1)
          LLVM_VERSION_MINOR=$(echo "${{ matrix.llvm-version }}" | cut -d '.' -f 2)
          LLVM_VERSION_REVISION=$(echo "${{ matrix.llvm-version }}" | cut -d '.' -f 3)
          EXTRA_CMAKE_ARGS=${{ matrix.llvm-configuration == 'slim' && '-DLLVM_LINK_LLVM_DYLIB=ON' || '' }}
          CONFIG_SUFFIX=${{ matrix.llvm-configuration == 'slim' && '-slim' || '' }}
          EOF
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.LLVM_VERSION_MAJOR }}${{ env.CONFIG_SUFFIX }}-${{ env.BASE_IMAGE_TAG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.LLVM_VERSION_MAJOR }}.${{ env.LLVM_VERSION_MINOR }}${{ env.CONFIG_SUFFIX }}-${{ env.BASE_IMAGE_TAG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.LLVM_VERSION_MAJOR }}.${{ env.LLVM_VERSION_MINOR }}.${{ env.LLVM_VERSION_REVISION }}${{ env.CONFIG_SUFFIX }}-${{ env.BASE_IMAGE_TAG }}
          platforms: ${{ env.PLATFORMS }}
          build-args: |
            BASE_IMAGE_TAG=${{ env.BASE_IMAGE_TAG }}
            BINUTILS_VERSION=${{ env.BINUTILS_VERSION }}
            CMAKE_VERSION=${{ env.CMAKE_VERSION }}
            LLVM_VERSION=${{ env.LLVM_VERSION }}
            EXTRA_CMAKE_ARGS=${{ env.EXTRA_CMAKE_ARGS }}
          push: true
